[package]
name = "ports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
backlog = { path = "../domains/backlog" }
thiserror = "1.0.30"
